/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb/index.vue')['default']
    AppForm: typeof import('./src/components/AppForm/index.vue')['default']
    AppSearchForm: typeof import('./src/components/AppSearchForm/index.vue')['default']
    ContentLoading: typeof import('./src/components/ContentLoading/index.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading/index.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    RequestMessageBridge: typeof import('./src/components/RequestMessageBridge/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLoadingBar: typeof import('./src/components/RouterLoadingBar/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    WatermarkOverlay: typeof import('./src/components/WatermarkOverlay/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AppBreadcrumb: typeof import('./src/components/AppBreadcrumb/index.vue')['default']
  const AppForm: typeof import('./src/components/AppForm/index.vue')['default']
  const AppSearchForm: typeof import('./src/components/AppSearchForm/index.vue')['default']
  const ContentLoading: typeof import('./src/components/ContentLoading/index.vue')['default']
  const GlobalLoading: typeof import('./src/components/GlobalLoading/index.vue')['default']
  const NInput: typeof import('naive-ui')['NInput']
  const NPagination: typeof import('naive-ui')['NPagination']
  const NSelect: typeof import('naive-ui')['NSelect']
  const RequestMessageBridge: typeof import('./src/components/RequestMessageBridge/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterLoadingBar: typeof import('./src/components/RouterLoadingBar/index.vue')['default']
  const RouterView: typeof import('vue-router')['RouterView']
  const WatermarkOverlay: typeof import('./src/components/WatermarkOverlay/index.vue')['default']
}